server.port=8084
spring.application.name=API-Gateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://USER-MS
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.server.webmvc.routes[1].id=account-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ACCOUNTMNG-MS
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/accounts/**